/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../shared/components/About.vue')['default']
    Auth: typeof import('./../shared/components/Auth.vue')['default']
    BaseButton: typeof import('./../shared/components/ui/BaseButton.vue')['default']
    BaseInput: typeof import('./../shared/components/ui/BaseInput.vue')['default']
    HelloWorld: typeof import('./../shared/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
